openapi: '3.0.1'
info:
  title: ProcessTasks API
  version: "1"
  description: API for managing Process Tasks

servers:
  - url: http://localhost:8888/api
    description: Local Server
paths:
  /process-tasks:
    get:
      summary: Get all process tasks
      operationId: getAllProcessTasks
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Number of records per page
          required: false
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Successfully retrieved process tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessTaskDTO'

    post:
      summary: Create new process tasks
      operationId: createProcessTasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ProcessTaskDTO'
      responses:
        200:
          description: Successfully created process tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessTaskDTO'

  /process-tasks/{id}:
    parameters:
      - name: id
        in: path
        description: Unique ID of the process task
        required: true
        schema:
          type: integer
    get:
      summary: Get a process task by ID
      operationId: getProcessTaskById
      responses:
        200:
          description: Successfully retrieved the process task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessTaskDTO'

    put:
      summary: Update an existing process task
      operationId: updateProcessTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessTaskDTO'
      responses:
        200:
          description: Successfully updated the process task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessTaskDTO'

    delete:
      summary: Delete a process task by ID
      operationId: deleteProcessTaskById
      responses:
        200:
          description: Successfully deleted the process task
          content:
            application/json:
              schema:
                type: string
                example: "Task deleted successfully"

  /process-instance-tasks:
    get:
      summary: Retrieve all process instance tasks
      operationId: getAllProcessInstanceTasks
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Number of records per page
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: A list of process instance tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessInstanceTaskDTO'

    post:
      summary: Create a new process instance task
      operationId: createProcessInstanceTasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: '#/components/schemas/ProcessInstanceTaskDTO'
      responses:
        '201':
          description: Successfully created process instance task
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/ProcessInstanceTaskDTO'

  /process-instance-tasks/{id}:
    parameters:
      - name: id
        in: path
        description: Unique ID of the process instance task
        required: true
        schema:
          type: integer
    get:
      summary: Get a specific process instance task by ID
      operationId: getProcessInstanceTaskById
      responses:
        '200':
          description: Process instance task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessInstanceTaskDTO'

    put:
      summary: Update a process instance task by ID
      operationId: updateProcessInstanceTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessInstanceTaskDTO'
      responses:
        '200':
          description: Successfully updated process instance task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessInstanceTaskDTO'
    delete:
      summary: Delete a process instance task by ID
      operationId: deleteProcessInstanceTaskById
      responses:
        200:
          description: Successfully deleted the process instance task
          content:
            application/json:
              schema:
                type: string
                example: "Process Instance Task deleted successfully"

components:
  schemas:
    ProcessTaskDTO:
      type: object
      description: Data element for ProcessTask
      required:
        - processId
        - name
      properties:
        id:
          type: integer
          format: int32
        processId:
          type: integer
          format: int32
          description: Unique ID of the process
        name:
          type: string
          description: Name of the process task
        description:
          type: string
          description: Description of the process task
        minutesToComplete:
          type: integer
          format: int32
          description: Estimated minutes to complete the task
        minutesToAssign:
          type: integer
          format: int32
          description: Minutes required to assign the task
        requestParam:
          type: string
          description: Request parameters associated with the task
        taskId:
          type: integer
          format: int32
          description: Unique ID of the task
        defaultPriority:
          type: integer
          format: int32
          description: Default priority of the task
        filter:
          type: string
          description: Filter conditions for the task
        userId:
          type: integer
          format: int32
          description: ID of the associated user
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the task was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
        createdBy:
          type: integer
          format: int32
          description: ID of the user who created the task
        updatedBy:
          type: integer
          format: int32
          description: ID of the user who last updated the task
        deleted:
          type: integer
          default: 0
          description: Soft delete flag (1 if deleted)
        realmId:
          type: integer
          description: Realm Id
        externalId:
          type: integer
          description: External ID
        alternateName:
          type: string
          description: Alternate Name a process task can have
        title:
          type: string
          description: Title of process task
        tags:
          type: array
          items:
            type: string
          description: List of tags for the task
        approvedBy:
          type: string
          description: One who approves the process task
        approvedAt:
          type: string
          description: Task Approved At Timestamp
        deletedBy:
          type: string
          description: Task Deleted by User Id
        deletedAt:
          type: string
          description: Task Deleted At Timestamp
        isActive:
          type: boolean
          description: Is process task active
        formTitle:
          type: string
          description: Form Title
        formIntroduction:
          type: string
          description: Form Introduction
        formDetails:
          type: string
          description: Form Details
        fixedAmount:
          type: number
          description: Fixed Amount
        amountFormField:
          type: number
          description: Amount Form Field
        stage:
          type: integer
          description: Stage
        totalFormFields:
          type: integer
          description: Total Form Fields

        language:  # Corrected indentation (moved outside of formMeta)
          type: string
          enum:
            - English
            - Hindi
            - Tamil
            - Telugu
            - Kannada
            - Marathi
            - Punjabi
            - Gujarati
            - Bengali
            - Malayalam
          description: Language for the form

    ProcessInstanceTaskDTO:
      type: object
      properties:
        id:
          type: integer
        processInstanceId:
          type: integer
        processTaskId:
          type: integer
        userId:
          type: integer
        assignedTo:
          type: integer
        nextAssignedTo:
          type: integer
        assignedAt:
          type: string
          format: date-time
        name:
          type: string
        description:
          type: string
        type:
          type: integer
        priority:
          type: integer
        status:
          type: string
          enum:
            - PENDING
            - IN_PROGRESS
            - COMPLETED
            - POSTPONED
        startDate:
          type: string
          format: date-time
        dueDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        postponedDate:
          type: string
          format: date-time
        taskDate:
          type: string
          format: date-time
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
        updatedBy:
          type: integer
        deleted:
          type: integer
          default: 0
          description: Soft delete flag (1 if deleted)
